export const allProducts = [
  {
    id: 1,
    image: "assets/images/decathlon-jecket/jens decathlons jacket.avif",
    imageDetails: {
      img1: "assets/images/decathlon-jecket/img1.webp",
      img2: "assets/images/decathlon-jecket/img2.webp",
      img4: "assets/images/decathlon-jecket/img3.webp",
      img5: "assets/images/decathlon-jecket/img4.webp",
    },
    name: "Jens Jecathlons Jacket",
    price: 599.99,
    quantity: 10,
    category: "Male",
    rating: 4.5,
    colors: ["#1e293b", "#374151", "#64748b"],
    sizes: ["S", "M", "L", "XL"],
    discountPercent: 20,
    description: {
      intro:
        "The Jens Jecathlons Jacket is built for performance and everyday style. Crafted from durable, weather-resistant fabric, it keeps you warm without compromising on movement.",
      details: [
        "Water-resistant outer shell",
        "Fleece-lined interior",
        "Two side pockets with zip closure",
        "Adjustable cuffs and hem",
        "Regular fit",
      ],
    },
  },
  {
    id: 2,
    image: "assets/images/ladies-coat/ladies casual coat.webp",
    imageDetails: {
      img1: "assets/images/ladies-coat/ladies casual coat.webp",
      img2: "assets/images/ladies-coat/img2.webp",
      img4: "assets/images/ladies-coat/img3.webp",
      img5: "assets/images/ladies-coat/img4.webp",
    },
    name: "Ladies Casual Coat",
    price: 429.99,
    quantity: 10,
    category: "Female",
    rating: 4.0,
    colors: ["#d6d3d1", "#1e293b", "#854d0e"],
    sizes: ["XS", "S", "M", "L"],
    discountPercent: 15,
    description: {
      intro:
        "A timeless casual coat designed for the modern woman. Clean lines and a relaxed silhouette make this coat effortlessly versatile for any occasion.",
      details: [
        "Mid-length cut",
        "Single-breasted button front",
        "Two front pockets",
        "Dry clean only",
        "Relaxed fit",
      ],
    },
  },
  {
    id: 3,
    image: "assets/images/ladies-jackets.webp",
    name: "Ladies jacket",
    price: 329.99,
    quantity: 5,
    category: "Female",
    rating: 4.2,
    colors: ["#92400e", "#1e293b", "#dc2626"],
    sizes: ["XS", "S", "M", "L"],
    description: {
      intro:
        "A stylish ladies jacket that pairs effortlessly with both casual and semi-formal outfits. Lightweight and breathable for all-day comfort.",
      details: [
        "Lightweight fabric",
        "Zip-up front closure",
        "Slim-fit design",
        "Machine washable",
        "Ribbed cuffs and hem",
      ],
    },
  },
  {
    id: 4,
    image: "assets/images/ladies-skirts.webp",
    name: "ladies Skirt",
    price: 179.99,
    quantity: 14,
    category: "Female",
    rating: 4.3,
    colors: ["#000", "#6b7280", "#fef3c7"],
    sizes: ["XS", "S", "M", "L", "XL"],
    discountPercent: 10,
    description: {
      intro:
        "A flowy midi skirt designed to move beautifully with every step. The relaxed waistband and soft fabric make it ideal for everyday wear.",
      details: [
        "Elastic waistband",
        "Midi length",
        "Soft woven fabric",
        "Machine washable",
        "Regular fit",
      ],
    },
  },
  {
    id: 5,
    image: "assets/images/jens-jeans.webp",
    name: "Mens Jeans",
    price: 259.99,
    quantity: 8,
    category: "Male",
    rating: 4.1,
    colors: ["#1e40af", "#1e293b", "#d1d5db"],
    sizes: ["28", "30", "32", "34", "36"],
    discountPercent: 25,
    description: {
      intro:
        "Classic men's denim jeans crafted from premium stretch cotton. Combines durability with a modern slim silhouette for everyday style.",
      details: [
        "98% cotton, 2% elastane",
        "Slim fit",
        "Five-pocket design",
        "Button fly",
        "Machine washable at 30°C",
      ],
    },
  },
  {
    id: 6,
    image: "assets/images/top-ware.webp",
    name: "Ladies Topware",
    price: 139.99,
    quantity: 12,
    category: "Female",
    rating: 4.4,
    colors: ["#fff", "#f4a7b9", "#d1fae5"],
    sizes: ["XS", "S", "M", "L"],
    description: {
      intro:
        "A lightweight and breathable ladies top perfect for warm weather. The relaxed silhouette flatters all body types and pairs easily with jeans or skirts.",
      details: [
        "100% viscose",
        "Relaxed fit",
        "Round neckline",
        "Machine washable",
        "Available in multiple colours",
      ],
    },
  },
  {
    id: 7,
    image: "assets/images/mens t-shirts.webp",
    name: "Mens T-shirt",
    price: 119.99,
    quantity: 20,
    category: "Male",
    rating: 4.0,
    colors: ["#fff", "#1e293b", "#6366f1"],
    sizes: ["S", "M", "L", "XL", "XLL"],
    discountPercent: 30,
    description: {
      intro:
        "An essential everyday T-shirt made from soft combed cotton. The breathable fabric and clean design make it a wardrobe staple for any man.",
      details: [
        "100% combed cotton",
        "Regular fit",
        "Crew neck",
        "Preshrunk fabric",
        "Machine washable",
      ],
    },
  },
  {
    id: 8,
    image: "assets/images/mens-hoodi.webp",
    name: "Mens Hoodi",
    price: 339.99,
    quantity: 15,
    category: "Male",
    rating: 5.0,
    colors: ["#1e293b", "#64748b", "#f59e0b"],
    sizes: ["S", "M", "L", "XL", "XLL"],
    description: {
      intro:
        "A premium heavyweight hoodie designed for ultimate comfort. The brushed fleece interior keeps you warm while the modern cut ensures a stylish look.",
      details: [
        "80% cotton, 20% polyester",
        "Brushed fleece interior",
        "Kangaroo front pocket",
        "Drawstring hood",
        "Ribbed cuffs and hem",
      ],
    },
  },
  {
    id: 9,
    image: "assets/images/mens-sweeter.jpg",
    name: "Mens Sweeter",
    price: 144.99,
    quantity: 10,
    category: "Male",
    rating: 4.6,
    colors: ["#d6d3d1", "#fef3c7", "#1e293b"],
    sizes: ["S", "M", "L", "XL"],
    discountPercent: 20,
    description: {
      intro:
        "A cosy men's sweater knitted from premium merino wool blend. Elegant enough for smart-casual occasions, warm enough for cooler days.",
      details: [
        "60% merino wool, 40% acrylic",
        "Regular fit",
        "Crew neck",
        "Ribbed cuffs and hem",
        "Hand wash recommended",
      ],
    },
  },
  {
    id: 10,
    image: "assets/images/mens-leather-jacket.webp",
    name: "Mens Jeather Jacket",
    price: 1229.99,
    quantity: 5,
    category: "Male",
    rating: 4.8,
    colors: ["#1e293b", "#92400e", "#374151"],
    sizes: ["S", "M", "L", "XL"],
    description: {
      intro:
        "A genuine leather jacket that defines timeless cool. The supple leather softens with wear, making every jacket uniquely yours over time.",
      details: [
        "100% genuine leather",
        "Viscose lining",
        "YKK zip closure",
        "Two side pockets",
        "Regular fit",
      ],
    },
  },
  {
    id: 11,
    image: "assets/images/ladies-sweeter.jpg",
    name: "ladies Sweeter",
    price: 179.99,
    quantity: 8,
    category: "Female",
    rating: 4.7,
    colors: ["#f4a7b9", "#fef3c7", "#d1fae5"],
    sizes: ["XS", "S", "M", "L"],
    discountPercent: 15,
    description: {
      intro:
        "A soft and elegant ladies sweater with a feminine silhouette. Perfect for layering or wearing on its own on cooler days.",
      details: [
        "50% wool, 50% acrylic",
        "Slim fit",
        "V-neck design",
        "Ribbed hem and cuffs",
        "Hand wash cold",
      ],
    },
  },
  {
    id: 12,
    image: "assets/images/mens-suede-shoe.webp",
    name: "Mens Suedue Shoe",
    price: 689.99,
    quantity: 12,
    category: "Male",
    rating: 4.3,
    colors: ["#92400e", "#1e293b", "#d6d3d1"],
    sizes: ["40", "41", "42", "43", "44", "45"],
    discountPercent: 18,
    description: {
      intro:
        "Crafted from premium suede, these men's shoes deliver refined style with exceptional comfort. The cushioned insole ensures all-day wearability.",
      details: [
        "Premium suede upper",
        "Leather lining",
        "Cushioned insole",
        "Rubber outsole",
        "Lace-up closure",
      ],
    },
  },
  {
    id: 13,
    image: "assets/images/mens-shorts.webp",
    name: "Mens short",
    price: 139.99,
    quantity: 20,
    category: "Male",
    rating: 4.2,
    colors: ["#1e293b", "#64748b", "#f59e0b"],
    sizes: ["S", "M", "L", "XL", "XLL"],
    discountPercent: 40,
    description: {
      intro:
        "Lightweight and comfortable men's shorts designed for warm weather. The quick-dry fabric makes these ideal for sport, travel, or leisure.",
      details: [
        "100% polyester quick-dry",
        "Elastic waistband with drawstring",
        "Two side pockets",
        "Regular fit",
        "Machine washable",
      ],
    },
  },
  {
    id: 14,
    image: "assets/images/mens-partyware-shoe.webp",
    name: "Mens Partyware Shoe",
    price: 599.99,
    quantity: 18,
    category: "Male",
    rating: 4.9,
    colors: ["#1e293b", "#92400e"],
    sizes: ["40", "41", "42", "43", "44"],
    description: {
      intro:
        "Elegant men's party shoes designed to make an impression. The polished leather upper and cushioned sole ensure you look sharp and feel comfortable throughout the night.",
      details: [
        "Polished leather upper",
        "Memory foam insole",
        "Leather lining",
        "Non-slip rubber outsole",
        "Slip-on design",
      ],
    },
  },
  {
    id: 15,
    image: "assets/images/Cheyanne - Elegant cashmere sweater for women.webp",
    name: "Cheyanne - Elegant cashmere sweater for women",
    price: 189.99,
    quantity: 10,
    category: "Female",
    rating: 4.5,
    colors: ["#f4a7b9", "#fef3c7", "#d1fae5", "#e0e7ff"],
    sizes: ["XS", "S", "M", "L"],
    discountPercent: 12,
    description: {
      intro:
        "The Cheyanne cashmere sweater is the epitome of luxury comfort. Spun from the finest cashmere fibres, it delivers unmatched softness and warmth with understated elegance.",
      details: [
        "100% Grade A cashmere",
        "Relaxed fit",
        "Crew neckline",
        "Dropped shoulders",
        "Dry clean only",
      ],
    },
  },
  {
    id: 16,
    image: "assets/images/guess-skeaker.avif",
    name: "Guess Skeaker",
    price: 599.99,
    quantity: 10,
    category: "Female",
    rating: 4.6,
    colors: ["#fff", "#f4a7b9", "#1e293b"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    description: {
      intro:
        "A signature Guess sneaker combining fashion-forward design with everyday comfort. The cushioned sole and premium materials make these a must-have.",
      details: [
        "Faux leather upper",
        "Branded logo detail",
        "Cushioned footbed",
        "Lace-up closure",
        "Rubber outsole",
      ],
    },
  },
  {
    id: 17,
    image: "assets/images/addidas-bags.avif",
    name: "Addidas Bags",
    price: 159.99,
    quantity: 13,
    category: "Female",
    rating: 4.4,
    colors: ["#1e293b", "#dc2626", "#fff"],
    sizes: ["One Size"],
    description: {
      intro:
        "The Adidas bag is built for active lifestyles. Spacious, durable, and stylish — it fits everything you need for the gym, commute, or weekend getaway.",
      details: [
        "Ripstop fabric exterior",
        "Multiple compartments",
        "Padded shoulder straps",
        "Water bottle side pocket",
        "Zip closure main compartment",
      ],
    },
  },
  {
    id: 18,
    image: "assets/images/addidas-short.avif",
    name: "Addidas Short",
    price: 259.99,
    quantity: 7,
    category: "Unisex",
    rating: 4.7,
    colors: ["#1e293b", "#fff", "#6366f1"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: {
      intro:
        "Adidas performance shorts engineered for sport and movement. The lightweight fabric and ergonomic cut allow full range of motion during any activity.",
      details: [
        "100% recycled polyester",
        "Moisture-wicking",
        "Inner brief lining",
        "Elastic waistband",
        "Side zip pockets",
      ],
    },
  },
  {
    id: 19,
    image: "assets/images/hawkers-sunglasses.avif",
    name: "Hawkers Sunglasses",
    price: 359.99,
    quantity: 5,
    category: "Male",
    rating: 4.8,
    colors: ["#1e293b", "#92400e", "#166534"],
    sizes: ["One Size"],
    description: {
      intro:
        "Hawkers sunglasses deliver premium UV protection with contemporary design. Lightweight frames and polarised lenses reduce glare for comfortable all-day wear.",
      details: [
        "Polarised lenses",
        "UV400 protection",
        "TR90 lightweight frame",
        "Spring hinges",
        "Includes protective case",
      ],
    },
  },
  {
    id: 20,
    image: "assets/images/hugo-t-shirt.avif",
    name: "Hugo T-Shirt",
    price: 349.99,
    quantity: 10,
    category: "Male",
    rating: 4.5,
    colors: ["#fff", "#1e293b", "#374151"],
    sizes: ["S", "M", "L", "XL", "XLL"],
    description: {
      intro:
        "A Hugo Boss premium T-shirt made from smooth Pima cotton. The refined cut and logo detailing elevate this essential to luxury casual wear.",
      details: [
        "100% Pima cotton",
        "Slim fit",
        "Embossed logo at chest",
        "Crew neck",
        "Machine washable 30°C",
      ],
    },
  },
  {
    id: 21,
    image: "assets/images/allsaint.avif",
    name: "AllSaints Braslet",
    price: 159.99,
    quantity: 15,
    category: "Female",
    rating: 4.7,
    colors: ["#92400e", "#1e293b", "#d1d5db"],
    sizes: ["One Size"],
    description: {
      intro:
        "An AllSaints signature bracelet combining raw materials with artisan craftsmanship. Wear alone or stack with other pieces for a layered effect.",
      details: [
        "Sterling silver hardware",
        "Adjustable clasp",
        "Vegan leather cord",
        "Unisex design",
        "Gift box included",
      ],
    },
  },
  {
    id: 22,
    image: "assets/images/armani-watch.avif",
    name: "Armani Watch",
    price: 1259.99,
    quantity: 5,
    category: "Male",
    rating: 4.9,
    colors: ["#1e293b", "#92400e"],
    sizes: ["One Size"],
    description: {
      intro:
        "An Armani Exchange timepiece that combines Italian craftsmanship with contemporary design. The stainless steel case and leather strap deliver sophistication for every occasion.",
      details: [
        "Stainless steel case",
        "Genuine leather strap",
        "Japanese quartz movement",
        "50m water resistance",
        "Scratch-resistant mineral glass",
      ],
    },
  },
  {
    id: 23,
    image: "assets/images/dr-martens-boots.avif",
    name: "Dr. Martens Boots",
    price: 959.99,
    quantity: 8,
    category: "Male",
    rating: 4.6,
    colors: ["#1e293b", "#92400e"],
    sizes: ["40", "41", "42", "43", "44", "45"],
    description: {
      intro:
        "The iconic Dr. Martens boots — built to last a lifetime. Made from Smooth leather with the signature yellow welt stitch and air-cushioned sole.",
      details: [
        "Smooth leather upper",
        "Air-cushioned sole",
        "Heat-sealed stitching",
        "Textile lining",
        "Goodyear welt construction",
      ],
    },
  },
  {
    id: 24,
    image: "assets/images/dr-martens-chelse.avif",
    name: "Dr. Martens Chelsea Boots",
    price: 779.99,
    quantity: 10,
    category: "Male",
    rating: 4.8,
    colors: ["#1e293b", "#92400e", "#374151"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    description: {
      intro:
        "Dr. Martens Chelsea Boots reimagined in the brand's signature style. Slip-on convenience meets robust construction for effortless everyday wear.",
      details: [
        "Smooth leather upper",
        "Elastic side panels",
        "Air-cushioned sole",
        "Grooved rubber outsole",
        "Pull tab at back",
      ],
    },
  },
  {
    id: 25,
    image: "assets/images/tomy-jeans-sneaker.avif",
    name: "Tomy Jeans Sneaker",
    price: 449.99,
    quantity: 12,
    category: "Male",
    rating: 4.5,
    colors: ["#fff", "#1e293b", "#6366f1"],
    sizes: ["40", "41", "42", "43", "44"],
    description: {
      intro:
        "Tommy Jeans sneakers that fuse streetwear attitude with premium construction. The chunky sole and logo branding deliver an unmistakable look.",
      details: [
        "Leather and textile upper",
        "Branded tongue and heel tab",
        "Cushioned footbed",
        "Chunky rubber outsole",
        "Lace-up closure",
      ],
    },
  },
  {
    id: 26,
    image: "assets/images/tommy-hilfiger-cap.avif",
    name: "Tommy Hilfiger Cap",
    price: 159.99,
    quantity: 20,
    category: "Unisex",
    rating: 4.3,
    colors: ["#1e293b", "#dc2626", "#fff"],
    sizes: ["One Size"],
    description: {
      intro:
        "A classic Tommy Hilfiger baseball cap with the iconic flag logo. Adjustable fit and premium cotton construction for everyday casual wear.",
      details: [
        "100% cotton twill",
        "Structured crown",
        "Embroidered logo",
        "Adjustable back strap",
        "Curved brim",
      ],
    },
  },
  {
    id: 27,
    image: "assets/images/tommy-bag.avif",
    name: "Tommy Bag",
    price: 139.99,
    quantity: 15,
    category: "Unisex",
    rating: 4.6,
    colors: ["#1e293b", "#92400e", "#d6d3d1"],
    sizes: ["One Size"],
    description: {
      intro:
        "A Tommy Hilfiger tote bag that combines practicality with preppy style. Spacious enough for daily essentials with the signature TH branding.",
      details: [
        "Polyester canvas",
        "Double top handles",
        "Interior zip pocket",
        "Logo charm",
        "Magnetic snap closure",
      ],
    },
  },
  {
    id: 28,
    image: "assets/images/timberland-boots.webp",
    name: "Timberland Boots",
    price: 1249.99,
    quantity: 10,
    category: "Female",
    rating: 4.7,
    colors: ["#92400e", "#d6d3d1", "#1e293b"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    description: {
      intro:
        "The iconic Timberland boot — engineered for the outdoors, embraced by streetwear culture. Waterproof construction and anti-fatigue technology for lasting comfort.",
      details: [
        "Waterproof premium nubuck leather",
        "Anti-fatigue footbed",
        "Seam-sealed waterproof construction",
        "Rubber lug outsole",
        "Padded collar for ankle support",
      ],
    },
  },
  {
    id: 29,
    image: "assets/images/polo-sneaker.avif",
    name: "Polo Sneaker",
    price: 159.99,
    quantity: 18,
    category: "Unisex",
    rating: 4.4,
    colors: ["#fff", "#1e293b", "#dc2626"],
    sizes: ["36", "37", "38", "39", "40", "41", "42"],
    description: {
      intro:
        "Ralph Lauren Polo sneakers that deliver classic American preppy style. Clean lines, quality materials, and the iconic Polo pony make these a timeless choice.",
      details: [
        "Leather and canvas upper",
        "Polo pony embroidery",
        "OrthoLite cushioned insole",
        "Rubber outsole",
        "Lace-up closure",
      ],
    },
  },
  {
    id: 30,
    image: "assets/images/northface-jacket.avif",
    name: "Northface Jacket",
    price: 1559.99,
    quantity: 5,
    category: "Unisex",
    rating: 4.9,
    colors: ["#1e293b", "#166534", "#dc2626"],
    sizes: ["XS", "S", "M", "L", "XL", "XLL"],
    description: {
      intro:
        "The North Face flagship jacket — engineered for extreme conditions. 700-fill power down insulation and a DryVent shell deliver exceptional warmth and weatherproofing.",
      details: [
        "DryVent 2L waterproof shell",
        "700-fill power down insulation",
        "Helmet-compatible hood",
        "Internal storm flap",
        "Stows in hand pocket",
      ],
    },
  },
  {
    id: 31,
    image: "assets/images/nike-sportware.avif",
    name: "Nike Sportware",
    price: 559.99,
    quantity: 10,
    category: "Unisex",
    rating: 4.5,
    colors: ["#1e293b", "#fff", "#dc2626"],
    sizes: ["S", "M", "L", "XL"],
    description: {
      intro:
        "Nike Sportswear clothing built to bridge the gap between the gym and the street. Lightweight Dri-FIT technology keeps you cool during training and relaxed after.",
      details: [
        "Dri-FIT moisture-wicking fabric",
        "Relaxed fit",
        "Elastic waistband",
        "Small Swoosh logo",
        "Machine washable",
      ],
    },
  },
  {
    id: 32,
    image: "assets/images/nike-sneaker.avif",
    name: "Nike Sneaker",
    price: 739.99,
    quantity: 12,
    category: "Unisex",
    rating: 4.7,
    colors: ["#fff", "#1e293b", "#6366f1"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    description: {
      intro:
        "Nike Air Max sneakers with responsive cushioning and iconic Air unit visible in the heel. The breathable mesh upper ensures comfort from morning to night.",
      details: [
        "Engineered mesh upper",
        "Max Air unit in heel",
        "Foam midsole",
        "Rubber waffle outsole",
        "Padded collar",
      ],
    },
  },
  {
    id: 33,
    image: "assets/images/levi's-belt.avif",
    name: "Levi's Belt",
    price: 159.99,
    quantity: 20,
    category: "Male",
    rating: 4.3,
    colors: ["#1e293b", "#92400e"],
    sizes: ["S", "M", "L", "XL"],
    description: {
      intro:
        "A Levi's genuine leather belt with the signature Batwing logo buckle. Classic, durable, and designed to complement any pair of Levi's jeans.",
      details: [
        "Full-grain genuine leather",
        "Nickel-free alloy buckle",
        "Batwing logo detail",
        "Width: 38mm",
        "Available in multiple sizes",
      ],
    },
  },
  {
    id: 34,
    image: "assets/images/karl-lagerfeld-sneaker.avif",
    name: "Karl Lagerfeld Sneaker",
    price: 1149.99,
    quantity: 8,
    category: "Female",
    rating: 4.8,
    colors: ["#fff", "#f4a7b9", "#1e293b"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    description: {
      intro:
        "Karl Lagerfeld sneakers that marry Parisian elegance with modern streetwear. The signature Ikonik Karl face and luxurious materials set these apart from the crowd.",
      details: [
        "Leather upper with Karl embossing",
        "Memory foam insole",
        "Metallic hardware details",
        "Platform rubber outsole",
        "Lace-up with logo-pull",
      ],
    },
  },
  {
    id: 35,
    image:
      "assets/images/ladies-gown/Florence – Elegant and refined one-shoulder satin dress.webp",
    imageDetails: {
      img1: "assets/images/ladies-gown/img1.jpg",
      img2: "assets/images/ladies-gown/img2.webp",
      img4: "assets/images/ladies-gown/img4.webp",
      img5: "assets/images/ladies-gown/img5.webp",
    },
    name: "Florence – Elegant and refined one-shoulder satin dress",
    price: 549.99,
    quantity: 8,
    category: "Female",
    rating: 4.8,
    colors: ["#dc2626", "#1e293b", "#f4a7b9"],
    sizes: ["XS", "S", "M", "L"],
    discountPercent: 22,
    description: {
      intro:
        "The Florence dress is the embodiment of refined evening elegance. A fluid one-shoulder silhouette in lustrous satin drapes beautifully for formal occasions.",
      details: [
        "100% satin polyester",
        "One-shoulder neckline",
        "Side split hem",
        "Fully lined",
        "Dry clean recommended",
      ],
    },
  },
];

const VAT_RATE = 0.15;

export function calculateVAT(price) {
  return price * VAT_RATE;
}
