export const allProducts = [
  {
    id: 1,
    image: "assets/images/jens decathlons jacket.avif",
    name: "Jens Jecathlons Jacket",
    price: 299.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Male",
    rating: 4.5,
  },
  {
    id: 2,
    image: "assets/images/ladies casual coat.webp",
    name: "Ladies Casual Coat",
    price: 129.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Female",
    rating: 4.0,
  },
  {
    id: 3,
    image: "assets/images/ladies-jackets.webp",
    name: "Ladies jacket",
    price: 229.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 5,
    category: "Female",
    rating: 4.2,
  },
  {
    id: 4,
    image: "assets/images/ladies-skirts.webp",
    name: "ladies Skirt",
    price: 79.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 14,
    category: "Female",
    rating: 4.3,
  },
  {
    id: 5,
    image: "assets/images/jens-jeans.webp",
    name: "Mens Jeans",
    price: 59.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 8,
    category: "Male",
    rating: 4.1,
  },
  {
    id: 6,
    image: "assets/images/top-ware.webp",
    name: "Ladies Topware",
    price: 39.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 12,
    category: "Female",
    rating: 4.4,
  },
  {
    id: 7,
    image: "assets/images/mens t-shirts.webp",
    name: "Mens T-shirt",
    price: 19.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 20,
    category: "Male",
    rating: 4.0,
  },
  {
    id: 8,
    image: "assets/images/mens-hoodi.webp",
    name: "Mens Hoodi",
    price: 39.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 15,
    category: "Male",
    rating: 5.0,
  },
  {
    id: 9,
    image: "assets/images/mens-sweeter.jpg",
    name: "Mens Sweeter",
    price: 44.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Male",
    rating: 4.6,
  },
  {
    id: 10,
    image: "assets/images/mens-leather-jacket.webp",
    name: "Mens Jeather Jacket",
    price: 229.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 5,
    category: "Male",
    rating: 4.8,
  },
  {
    id: 11,
    image: "assets/images/ladies-sweeter.jpg",
    name: "ladies Sweeter",
    price: 79.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 8,
    category: "Female",
    rating: 4.7,
  },
  {
    id: 12,
    image: "assets/images/mens-suede-shoe.webp",
    name: "Mens Suedue Shoe",
    price: 89.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 12,
    category: "Male",
    rating: 4.3,
  },
  {
    id: 13,
    image: "assets/images/mens-shorts.webp",
    name: "Mens short",
    price: 39.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 20,
    category: "Male",
    rating: 4.2,
  },
  {
    id: 14,
    image: "assets/images/mens-partyware-shoe.webp",
    name: "Mens Partyware Shoe",
    price: 199.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 18,
    category: "Male",
    rating: 4.9,
  },
  {
    id: 15,
    image: "assets/images/Cheyanne - Elegant cashmere sweater for women.webp",
    name: "Cheyanne - Elegant cashmere sweater for women",
    price: 129.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Female",
    rating: 4.5,
  },
  {
    id: 16,
    image: "assets/images/guess-skeaker.avif",
    name: "Guess Skeaker",
    price: 599.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Female",
    rating: 4.6,
  },

  {
    id: 17,
    image: "assets/images/addidas-bags.avif",
    name: "Addidas Bags",
    price: 159.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 13,
    category: "Female",
    rating: 4.4,
  },

  {
    id: 18,
    image: "assets/images/addidas-short.avif",
    name: "Addidas Short",
    price: 259.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 7,
    category: "Unisex",
    rating: 4.7,
  },

  {
    id: 19,
    image: "assets/images/hawkers-sunglasses.avif",
    name: "Hawkers Sunglasses",
    price: 359.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 5,
    category: "Male",
    rating: 4.8,
  },

  {
    id: 20,
    image: "assets/images/hugo-t-shirt.avif",
    name: "Hugo T-Shirt",
    price: 349.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Male",
    rating: 4.5,
  },

  {
    id: 21,
    image: "assets/images/allsaint.avif",
    name: "AllSaints Braslet",
    price: 159.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 15,
    category: "Female",
    rating: 4.7,
  },

  {
    id: 22,
    image: "assets/images/armani-watch.avif",
    name: "Armani Watch",
    price: 1259.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 5,
    category: "Male",
    rating: 4.9,
  },

  {
    id: 23,
    image: "assets/images/dr-martens-boots.avif",
    name: "Dr. Martens Boots",
    price: 959.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 8,
    category: "Male",
    rating: 4.6,
  },

  {
    id: 24,
    image: "assets/images/dr-martens-chelse.avif",
    name: "Dr. Martens Chelsea Boots",
    price: 779.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Male",
    rating: 4.8,
  },

  {
    id: 25,
    image: "assets/images/tomy-jeans-sneaker.avif",
    name: "Tomy Jeans Sneaker",
    price: 449.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 12,
    category: "Male",
    rating: 4.5,
  },

  {
    id: 26,
    image: "assets/images/tommy-hilfiger-cap.avif",
    name: "Tommy Hilfiger Cap",
    price: 159.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 20,
    category: "Unisex",
    rating: 4.3,
  },

  {
    id: 27,
    image: "assets/images/tommy-bag.avif",
    name: "Tommy Bag",
    price: 139.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 15,
    category: "Unisex",
    rating: 4.6,
  },

  {
    id: 28,
    image: "assets/images/timberland-boots.webp",
    name: "Timberland Boots",
    price: 1249.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Female",
    rating: 4.7,
  },

  {
    id: 29,
    image: "assets/images/polo-sneaker.avif",
    name: "Polo Sneaker",
    price: 159.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 18,
    category: "Unisex",
    rating: 4.4,
  },

  {
    id: 30,
    image: "assets/images/northface-jacket.avif",
    name: "Northface Jacket",
    price: 1559.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 5,
    category: "Unisex",
    rating: 4.9,
  },

  {
    id: 31,
    image: "assets/images/nike-sportware.avif",
    name: "Nike Sportware",
    price: 559.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 10,
    category: "Unisex",
    rating: 4.5,
  },

  {
    id: 32,
    image: "assets/images/nike-sneaker.avif",
    name: "Nike Sneaker",
    price: 739.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 12,
    category: "Unisex",
    rating: 4.7,
  },

  {
    id: 33,
    image: "assets/images/levi's-belt.avif",
    name: "Levi's Belt",
    price: 159.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 20,
    category: "Male",
    rating: 4.3,
  },

  {
    id: 34,
    image: "assets/images/karl-lagerfeld-sneaker.avif",
    name: "Karl Lagerfeld Sneaker",
    price: 1149.99,
    favorite: "assets/icons/icon-set/heart.png",
    quantity: 8,
    category: "Female",
    rating: 4.8,
  },
];

const VAT_RATE = 0.15;

export function calculateVAT(price) {
  return price * VAT_RATE;
}
